version: "3.8"
services: 
    mysql: 
        image: mysql:5.7
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_DATABASE: test
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
            - ./database:/data/db
        ports:
            - 3306:3306
        restart: unless-stopped
