version: "3.8"
services:
    mongodb:
        image : mongo:4.4
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
